const express =  require('express');
const router = express.Router();

const propertyController = require('../../controllers/Properties/properties');

router.get('/:cID', propertyController.getProperties);
router.get('/property/:pID', propertyController.getProperty);
router.patch('/property/:pID', propertyController.updateProperty);
router.patch('/property/:pID/TenantPayLessThanAmountDue', propertyController.updatePropertyTenantPayLessThanAmountDue);
router.patch('/property/:pID/AlertUpcomingLeaseExpiration', propertyController.updatePropertyAlertUpcomingLeaseExpiration);
router.patch('/property/:pID/AbsorbApplicationFee', propertyController.updatePropertyAbsorbApplicationFee);
router.patch('/property/:pID/NotifyWorkOrderChanges', propertyController.updatePropertyNotifyWorkOrderChanges);
router.patch('/property/:pID/NotifyWorkOrderChangesPM', propertyController.updatePropertyNotifyWorkOrderChangesPM);
router.patch('/property/:pID/RequireRenterInsurance', propertyController.updatePropertyRequireRenterInsurance);
router.patch('/property/:pID/ApplicantsDepositsPage', propertyController.updatePropertyApplicantsDepositsPage);
router.patch('/property/:pID/AlertPMDocSent', propertyController.updatePropertyAlertPMDocSent);
router.patch('/property/:pID/DisplayTenantConsent', propertyController.updatePropertyDisplayTenantConsent);
router.patch('/property/:pID/OfficeProperty', propertyController.updatePropertyOfficeProperty);
router.patch('/property/:pID/ReceivePromiss', propertyController.updatePropertyReceivePromiss);
router.patch('/property/:pID/LateFeesPercentage', propertyController.updatePropertyLateFeesPercentage);
router.patch('/property/:pID/Seattle', propertyController.updatePropertySeattle);
router.patch('/property/:pID/CloseOut', propertyController.updatePropertyCloseOut);
router.patch('/property/:pID/CloseOutCancel', propertyController.updatePropertyCloseOutCancel);
router.patch('/property/:pID/ProfitLossReport', propertyController.updatePropertyProfitLossReport);
router.get('/RecurringTaxes/:pID', propertyController.getRecurringTaxes);
router.post('/RecurringTaxes/:pID', propertyController.insertRecurringChargesTax);
router.patch('/RecurringTaxes', propertyController.updateRecurringChargesTax);
router.get('/OfficeHours/:pID', propertyController.getOfficeHours);
router.get('/PropertyOfficeHours/:pID', propertyController.getPropertyOfficeHours);
router.post('/PropertyOfficeHours/:pID', propertyController.insertPropertyOfficeHours);
router.patch('/PropertyOfficeHours', propertyController.updatePropertyOfficeHours);
router.get('/AutoBill/:pID', propertyController.getAutoBill);
router.post('/AutoBill/:pID', propertyController.insertAutoBill);
router.patch('/AutoBill/:pID', propertyController.updateAutoBill);
router.post('/AutoBillNotify/:pID', propertyController.insertAutoBillNotify);
router.patch('/AutoBillNotify/:pID', propertyController.updateAutoBillNotify);
router.get('/:cID/TenantPaymentAmountDueYesAllProperties', propertyController.getTenantPaymentAmountDueYesAllProperties);
router.get('/:cID/TenantPaymentAmountDueNoAllProperties', propertyController.getTenantPaymentAmountDueNoAllProperties);
router.patch('/:cID/TenantPayLessThanAmountDue', propertyController.updateTenantPayLessThanAmountDueAllProperties);
router.get('/:cID/AlertUpcomingLeaseExpiration', propertyController.getAlertUpcomingLeaseExpirationAllProperties);
router.patch('/:cID/AlertUpcomingLeaseExpiration', propertyController.updateAlertUpcomingLeaseExpirationAllProperties);
router.get('/:cID/AbsorbApplicationFee', propertyController.getAbsorbApplicationFee);
router.patch('/:cID/AbsorbApplicationFee', propertyController.updateAbsorbApplicationFeeAllProperties);
router.get('/:cID/NotifyWorkOrderChanges', propertyController.getNotifyWorkOrderChanges);
router.patch('/:cID/NotifyWorkOrderChanges', propertyController.updateNotifyWorkOrderChangesAllProperties);
router.get('/:cID/NotifyWorkOrderChangesPM', propertyController.getNotifyWorkOrderChangesPM);
router.patch('/:cID/NotifyWorkOrderChangesPM', propertyController.updateNotifyWorkOrderChangesPMAllProperties);
router.get('/:cID/CloseOutAllProp', propertyController.getCloseOutAllProp);
router.patch('/:cID/CloseOut', propertyController.updateCloseOutAllProperties);
router.patch('/:cID/CloseOutCancel', propertyController.updateCloseOutCancelAllProperties);
router.get('/:cID/ProfitLossReport', propertyController.getProfitLossReport);
router.patch('/:cID/ProfitLossReport', propertyController.updateProfitLossReportAllProperties);
router.get('/:cID/RequireInsuranceYes', propertyController.getRequireInsuranceYes);
router.get('/:cID/RequireInsuranceNo', propertyController.getRequireInsuranceNo);
router.patch('/:cID/RequireRenterInsurance', propertyController.updateRequireRenterInsuranceAllProperties);
router.get('/:cID/ApplicantsDepositPageYes', propertyController.getApplicantsDepositPageYes);
router.get('/:cID/ApplicantsDepositPageNo', propertyController.getApplicantsDepositPageNo);
router.patch('/:cID/ApplicantsDepositsPage', propertyController.updateApplicantsDepositsPageAllProperties);
router.get('/:cID/AlertPMDocSentYes', propertyController.getAlertPMDocSentYes);
router.get('/:cID/AlertPMDocSentNo', propertyController.getAlertPMDocSentNo);
router.patch('/:cID/AlertPMDocSent', propertyController.updateAlertPMDocSentAllProperties);
router.get('/:cID/TenantConsentYes', propertyController.getTenantConsentYes);
router.get('/:cID/TenantConsentNo', propertyController.getTenantConsentNo);
router.patch('/:cID/DisplayTenantConsent', propertyController.updateDisplayTenantConsentAllProperties);

module.exports = router;